export const cities = [{
    "capitol": "Warsaw",
    "country": "Poland"
},{
    'capitol': 'Amsterdam',
    'country': 'Netherlands'
}, {
    'capitol': 'Andorra la Vella',
    'country': 'Andorra'
}, {
    'capitol': 'Athens',
    'country': 'Greece'
}, {
    'capitol': 'Belgrade',
    'country': 'Serbia'
}, {
    'capitol': 'Berlin',
    'country': 'Germany'
}, {
    'capitol': 'Bern',
    'country': 'Switzerland'
}, {
    'capitol': 'Bratislava',
    'country': 'Slovakia'
}, {
    'capitol': 'Brussels',
    'country': 'Belgium'
}, {
    'capitol': 'Bucharest',
    'country': 'Romania'
}, {
    'capitol': 'Budapest',
    'country': 'Hungary'
}, {
    'capitol': 'Chisinau',
    'country': 'Moldova'
}, {
    'capitol': 'Copenhagen',
    'country': 'Denmark'
}, {
    'capitol': 'Douglas',
    'country': 'Isle of Man'
}, {
    'capitol': 'Dublin',
    'country': 'Ireland'
}, {
    'capitol': 'Gibraltar',
    'country': 'Gibraltar'
}, {
    'capitol': 'Helsinki',
    'country': 'Finland'
}, {
    'capitol': 'Kiev',
    'country': 'Ukraine'
}, {
    'capitol': 'Lisbon',
    'country': 'Portugal'
}, {
    'capitol': 'Ljubljana',
    'country': 'Slovenia'
}, {
    'capitol': 'London',
    'country': 'United Kingdom'
}, {
    'capitol': 'Longyearbyen',
    'country': 'Svalbard'
}, {
    'capitol': 'Luxembourg',
    'country': 'Luxembourg'
}, {
    'capitol': 'Madrid',
    'country': 'Spain'
}, {
    'capitol': 'Minsk',
    'country': 'Belarus'
}, {
    'capitol': 'Monaco',
    'country': 'Monaco'
}, {
    'capitol': 'Moscow',
    'country': 'Russia'
}, {
    'capitol': 'Oslo',
    'country': 'Norway'
}, {
    'capitol': 'Paris',
    'country': 'France'
}, {
    'capitol': 'Podgorica',
    'country': 'Montenegro'
}, {
    'capitol': 'Prague',
    'country': 'Czechia'
}, {
    'capitol': 'Pristina',
    'country': 'Kosovo'
}, {
    'capitol': 'Reykjavik',
    'country': 'Iceland'
}, {
    'capitol': 'Riga',
    'country': 'Latvia'
}, {
    'capitol': 'Rome',
    'country': 'Italy'
}, {
    'capitol': 'Saint Helier',
    'country': 'Jersey'
}, {
    'capitol': 'Saint Peter Port',
    'country': 'Guernsey'
}, {
    'capitol': 'San Marino',
    'country': 'San Marino'
}, {
    'capitol': 'Sarajevo',
    'country': 'Bosnia and Herzegovina'
}, {
    'capitol': 'Skopje',
    'country': 'North Macedonia'
}, {
    'capitol': 'Sofia',
    'country': 'Bulgaria'
}, {
    'capitol': 'Stockholm',
    'country': 'Sweden'
}, {
    'capitol': 'Tallinn',
    'country': 'Estonia'
}, {
    'capitol': 'Tirana',
    'country': 'Albania'
}, {
    'capitol': 'Tórshavn',
    'country': 'Faroe Islands'
}, {
    'capitol': 'Vaduz',
    'country': 'Liechtenstein'
}, {
    'capitol': 'Valletta',
    'country': 'Malta'
}, {
    'capitol': 'Vienna',
    'country': 'Austria'
}, {
    'capitol': 'Vilnius',
    'country': 'Lithuania'
}, {
    'capitol': 'Zagreb',
    'country': 'Croatia'
}
];
